version: "3.1"
services:
    db:
        image: mysql:5.7
        # utf-8を強制
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./volume/mysql:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
        env_file:
            - .env

    wordpress:
        image: wordpress:latest
        depends_on:
            - db
        links:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
            WORDPRESS_DB_USER: $WORDPRESS_DB_USER
            WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
        env_file: .env
        volumes:
            - ./volume/themes:/var/www/html/wp-content/themes
            - ./volume/plugins:/var/www/html/wp-content/plugins
            - ./volume/uploads:/var/www/html/wp-content/uploads

volumes:
    db-data: